/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CallsIndexRouteImport } from './routes/calls/index'
import { Route as FollowUpsIndexRouteImport } from './routes/follow-ups/index'
import { Route as LeadsIndexRouteImport } from './routes/leads/index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads/$leadId'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsIndexRoute = FollowUpsIndexRouteImport.update({
  id: '/follow-ups/',
  path: '/follow-ups/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/calls/': typeof CallsIndexRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/calls': typeof CallsIndexRoute
  '/follow-ups': typeof FollowUpsIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/calls/': typeof CallsIndexRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent'
    | '/login'
    | '/services'
    | '/settings'
    | '/leads/$leadId'
    | '/calls/'
    | '/follow-ups/'
    | '/leads/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent'
    | '/login'
    | '/services'
    | '/settings'
    | '/leads/$leadId'
    | '/calls'
    | '/follow-ups'
    | '/leads'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/ai-agent'
    | '/login'
    | '/services'
    | '/settings'
    | '/leads/$leadId'
    | '/calls/'
    | '/follow-ups/'
    | '/leads/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentRoute: typeof AiAgentRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  CallsIndexRoute: typeof CallsIndexRoute
  FollowUpsIndexRoute: typeof FollowUpsIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups/': {
      id: '/follow-ups/'
      path: '/follow-ups'
      fullPath: '/follow-ups/'
      preLoaderRoute: typeof FollowUpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentRoute: AiAgentRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  CallsIndexRoute: CallsIndexRoute,
  FollowUpsIndexRoute: FollowUpsIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
