# Generated by Django 4.2.30 on 2026-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='bussiness',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
