# Generated by Django 4.2.30 on 2026-08-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_followup_bussiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
