// Mock data store. Swap these arrays for Django REST responses later —
// the service modules are the only place components read data from.

export const PIPELINE_STAGES = [
  "New",
  "Contacted",
  "Interested",
  "Meeting",
  "Proposal",
  "Won",
  "Lost",
];

export const leads = [
  {
    id: "LD-1001",
    business: "Sharma Sweets & Namkeen",
    category: "Restaurant / Sweets",
    location: "Indore, MP",
    owner: "Rakesh Sharma",
    score: 88,
    website: "sharmasweets.in",
    phone: "+91 98260 41122",
    email: "rakesh@sharmasweets.in",
    status: "Interested",
    lastContact: "2026-08-10",
    nextFollowUp: "2026-08-12",
    instagram: "@sharmasweets_indore",
    googleRating: 4.6,
    reviews: 412,
    notes: "Wants online ordering before Diwali season.",
    audit: {
      mobileFriendly: false,
      https: true,
      pageSpeed: false,
      seoBasics: false,
      googleBusiness: true,
      onlineOrdering: false,
    },
  },
  {
    id: "LD-1002",
    business: "Kothari Dental Studio",
    category: "Healthcare / Clinic",
    location: "Pune, MH",
    owner: "Dr. Neha Kothari",
    score: 74,
    website: "",
    phone: "+91 90210 88345",
    email: "hello@kotharidental.com",
    status: "Meeting",
    lastContact: "2026-08-11",
    nextFollowUp: "2026-08-12",
    instagram: "@kothari.dental",
    googleRating: 4.9,
    reviews: 128,
    notes: "No website at all. Needs appointment booking.",
    audit: {
      mobileFriendly: false,
      https: false,
      pageSpeed: false,
      seoBasics: false,
      googleBusiness: true,
      onlineOrdering: false,
    },
  },
  {
    id: "LD-1003",
    business: "Vaibhav Interiors",
    category: "Interior Design",
    location: "Ahmedabad, GJ",
    owner: "Mihir Patel",
    score: 61,
    website: "vaibhavinteriors.co.in",
    phone: "+91 97370 22910",
    email: "mihir@vaibhavinteriors.co.in",
    status: "Contacted",
    lastContact: "2026-08-08",
    nextFollowUp: "2026-08-13",
    instagram: "@vaibhav.interiors",
    googleRating: 4.3,
    reviews: 76,
    notes: "Site exists but portfolio is outdated.",
    audit: {
      mobileFriendly: true,
      https: true,
      pageSpeed: false,
      seoBasics: false,
      googleBusiness: true,
      onlineOrdering: false,
    },
  },
  {
    id: "LD-1004",
    business: "Iyer Tax Consultants",
    category: "Finance / CA Firm",
    location: "Chennai, TN",
    owner: "S. Iyer",
    score: 45,
    website: "iyertax.in",
    phone: "+91 94440 71203",
    email: "office@iyertax.in",
    status: "New",
    lastContact: "",
    nextFollowUp: "2026-08-14",
    instagram: "",
    googleRating: 4.1,
    reviews: 31,
    notes: "",
    audit: {
      mobileFriendly: false,
      https: true,
      pageSpeed: true,
      seoBasics: false,
      googleBusiness: false,
      onlineOrdering: false,
    },
  },
  {
    id: "LD-1005",
    business: "FitZone Gym Kalyani Nagar",
    category: "Fitness",
    location: "Pune, MH",
    owner: "Aman Deshpande",
    score: 92,
    website: "fitzone-pune.com",
    phone: "+91 88888 40561",
    email: "aman@fitzone-pune.com",
    status: "Proposal",
    lastContact: "2026-08-11",
    nextFollowUp: "2026-08-11",
    instagram: "@fitzone.kalyaninagar",
    googleRating: 4.7,
    reviews: 289,
    notes: "Proposal sent — ₹65,000 revamp + membership portal.",
    audit: {
      mobileFriendly: true,
      https: true,
      pageSpeed: false,
      seoBasics: true,
      googleBusiness: true,
      onlineOrdering: false,
    },
  },
  {
    id: "LD-1006",
    business: "Bansal Coaching Classes",
    category: "Education",
    location: "Jaipur, RJ",
    owner: "Praveen Bansal",
    score: 55,
    website: "",
    phone: "+91 99280 33471",
    email: "bansalclasses@gmail.com",
    status: "Won",
    lastContact: "2026-08-05",
    nextFollowUp: "",
    instagram: "@bansalclasses",
    googleRating: 4.4,
    reviews: 54,
    notes: "Signed ₹48,000 website + admission form project.",
    audit: {
      mobileFriendly: false,
      https: false,
      pageSpeed: false,
      seoBasics: false,
      googleBusiness: true,
      onlineOrdering: false,
    },
  },
  {
    id: "LD-1007",
    business: "Nagpur Auto Spares",
    category: "Retail / Auto",
    location: "Nagpur, MH",
    owner: "Imran Sheikh",
    score: 28,
    website: "nagpurautospares.com",
    phone: "+91 70570 19983",
    email: "sales@nagpurautospares.com",
    status: "Lost",
    lastContact: "2026-07-29",
    nextFollowUp: "",
    instagram: "",
    googleRating: 3.8,
    reviews: 19,
    notes: "Budget too low for now. Revisit in Q4.",
    audit: {
      mobileFriendly: true,
      https: true,
      pageSpeed: true,
      seoBasics: true,
      googleBusiness: true,
      onlineOrdering: false,
    },
  },
  {
    id: "LD-1008",
    business: "Green Leaf Organics",
    category: "D2C / Grocery",
    location: "Bengaluru, KA",
    owner: "Divya Rao",
    score: 79,
    website: "greenleaforganics.in",
    phone: "+91 80889 62014",
    email: "divya@greenleaforganics.in",
    status: "Interested",
    lastContact: "2026-08-09",
    nextFollowUp: "2026-08-15",
    instagram: "@greenleaf.organics",
    googleRating: 4.5,
    reviews: 143,
    notes: "Wants Shopify → custom migration quote.",
    audit: {
      mobileFriendly: true,
      https: true,
      pageSpeed: false,
      seoBasics: true,
      googleBusiness: true,
      onlineOrdering: true,
    },
  },
];

export const calls = [
  {
    id: "CL-501",
    leadId: "LD-1005",
    business: "FitZone Gym Kalyani Nagar",
    date: "2026-08-11T11:20:00",
    duration: 412,
    result: "Interested",
    summary:
      "Aman confirmed budget of ₹60–70k. Wants membership portal with UPI payments. Asked for proposal by Thursday.",
    nextAction: "Send proposal PDF with 3 pricing tiers",
    transcript: [
      { speaker: "AI", text: "Hi Aman, calling about FitZone's website — is now a good time?" },
      { speaker: "Lead", text: "Yes, two minutes. What is this about?" },
      {
        speaker: "AI",
        text: "Your site loads in 6.2s on mobile and has no membership signup. I build fast fitness sites with UPI payments.",
      },
      { speaker: "Lead", text: "Interesting. What would something like that cost?" },
      { speaker: "AI", text: "Typically ₹55,000 to ₹70,000 depending on the member portal scope." },
      { speaker: "Lead", text: "Send me a proposal, that's within range." },
    ],
  },
  {
    id: "CL-502",
    leadId: "LD-1002",
    business: "Kothari Dental Studio",
    date: "2026-08-11T09:05:00",
    duration: 288,
    result: "Meeting Booked",
    summary:
      "Dr. Kothari has no website. Booked a video call for Aug 14, 4:30 PM to review appointment booking flow.",
    nextAction: "Prepare booking flow mockup before Aug 14",
    transcript: [
      { speaker: "AI", text: "Hello Doctor, do you currently take appointments online?" },
      { speaker: "Lead", text: "No, only on WhatsApp. It gets messy." },
      { speaker: "AI", text: "A simple booking page could cut that load. Can we do a short call Friday?" },
      { speaker: "Lead", text: "Friday 4:30 works." },
    ],
  },
  {
    id: "CL-503",
    leadId: "LD-1001",
    business: "Sharma Sweets & Namkeen",
    date: "2026-08-10T17:40:00",
    duration: 196,
    result: "Interested",
    summary: "Rakesh wants online ordering live before Diwali. Price-sensitive, asked for phased delivery.",
    nextAction: "Share phased quote (₹35k phase 1)",
    transcript: [
      { speaker: "AI", text: "Do customers ask you for online ordering?" },
      { speaker: "Lead", text: "Daily. But I need it before Diwali." },
      { speaker: "AI", text: "That's feasible in phases. I'll send options." },
    ],
  },
  {
    id: "CL-504",
    leadId: "LD-1003",
    business: "Vaibhav Interiors",
    date: "2026-08-08T15:10:00",
    duration: 94,
    result: "Callback Requested",
    summary: "Mihir was on site. Asked to call back next week after 5 PM.",
    nextAction: "Call back Aug 13 after 5 PM",
    transcript: [
      { speaker: "AI", text: "Is this a good time to talk about your portfolio site?" },
      { speaker: "Lead", text: "I'm at a site visit, call next week." },
    ],
  },
  {
    id: "CL-505",
    leadId: "LD-1007",
    business: "Nagpur Auto Spares",
    date: "2026-07-29T12:00:00",
    duration: 61,
    result: "Not Interested",
    summary: "Imran said budget is tight this quarter. Marked lost, revisit in Q4.",
    nextAction: "Revisit October",
    transcript: [{ speaker: "Lead", text: "No budget right now, sorry." }],
  },
];

export const followUps = [
  {
    id: "FU-301",
    leadId: "LD-1005",
    business: "FitZone Gym Kalyani Nagar",
    task: "Send proposal PDF (3 tiers)",
    due: "today",
    time: "05:30 PM",
    priority: "High",
    completed: false,
  },
  {
    id: "FU-302",
    leadId: "LD-1001",
    business: "Sharma Sweets & Namkeen",
    task: "Share phased quote for online ordering",
    due: "today",
    time: "07:00 PM",
    priority: "High",
    completed: false,
  },
  {
    id: "FU-303",
    leadId: "LD-1002",
    business: "Kothari Dental Studio",
    task: "Prepare booking flow mockup",
    due: "tomorrow",
    time: "11:00 AM",
    priority: "Medium",
    completed: false,
  },
  {
    id: "FU-304",
    leadId: "LD-1003",
    business: "Vaibhav Interiors",
    task: "Callback after 5 PM",
    due: "week",
    time: "05:15 PM",
    priority: "Medium",
    completed: false,
  },
  {
    id: "FU-305",
    leadId: "LD-1008",
    business: "Green Leaf Organics",
    task: "Send migration scope + timeline",
    due: "week",
    time: "12:00 PM",
    priority: "Medium",
    completed: false,
  },
  {
    id: "FU-306",
    leadId: "LD-1004",
    business: "Iyer Tax Consultants",
    task: "First intro call",
    due: "overdue",
    time: "Aug 09, 03:00 PM",
    priority: "Low",
    completed: false,
  },
  {
    id: "FU-307",
    leadId: "LD-1006",
    business: "Bansal Coaching Classes",
    task: "Collect content + logo files",
    due: "completed",
    time: "Aug 06",
    priority: "Medium",
    completed: true,
  },
];

export const projects = [
  {
    id: "PR-201",
    name: "Bansal Coaching — Website + Admissions",
    client: "Bansal Coaching Classes",
    leadId: "LD-1006",
    value: 48000,
    status: "Active",
    startDate: "2026-08-06",
    deadline: "2026-09-05",
    tasks: [
      { id: "t1", label: "Requirement doc signed", done: true },
      { id: "t2", label: "Design system + homepage mockup", done: true },
      { id: "t3", label: "Course & faculty pages", done: true },
      { id: "t4", label: "Admission form + WhatsApp lead alert", done: false },
      { id: "t5", label: "SEO basics + analytics", done: false },
      { id: "t6", label: "Deploy + client training", done: false },
    ],
  },
  {
    id: "PR-200",
    name: "Sheetal Boutique — Catalogue Site",
    client: "Sheetal Boutique",
    leadId: "",
    value: 32000,
    status: "Completed",
    startDate: "2026-06-18",
    deadline: "2026-07-20",
    tasks: [
      { id: "t1", label: "Catalogue build", done: true },
      { id: "t2", label: "WhatsApp enquiry flow", done: true },
      { id: "t3", label: "Handover", done: true },
    ],
  },
];

export const servicesCatalog = [
  {
    id: "SV-01",
    name: "Starter Business Website",
    description: "5-page responsive site, contact form, Google Business setup.",
    price: 24000,
    delivery: "7 days",
    active: true,
  },
  {
    id: "SV-02",
    name: "Business Website + SEO",
    description: "8–10 pages, on-page SEO, analytics, speed optimisation.",
    price: 45000,
    delivery: "14 days",
    active: true,
  },
  {
    id: "SV-03",
    name: "Booking / Appointment System",
    description: "Slot booking, reminders, admin panel.",
    price: 38000,
    delivery: "12 days",
    active: true,
  },
  {
    id: "SV-04",
    name: "Online Ordering (Restaurant)",
    description: "Menu, cart, UPI payments, order dashboard.",
    price: 55000,
    delivery: "18 days",
    active: true,
  },
  {
    id: "SV-05",
    name: "Website Care Plan",
    description: "Monthly updates, backups, uptime monitoring.",
    price: 3500,
    delivery: "Monthly",
    active: false,
  },
];

export const notifications = [
  {
    id: "N-1",
    title: "Follow-up due today",
    body: "FitZone Gym — send proposal PDF by 5:30 PM",
    time: "20 min ago",
    unread: true,
  },
  {
    id: "N-2",
    title: "Call summary ready",
    body: "Kothari Dental Studio — meeting booked Aug 14",
    time: "2 hours ago",
    unread: true,
  },
  {
    id: "N-3",
    title: "Lead score updated",
    body: "Green Leaf Organics moved from 68 → 79",
    time: "Yesterday",
    unread: false,
  },
];

export const weeklyActivity = [
  { day: "Mon", calls: 6, leads: 4 },
  { day: "Tue", calls: 9, leads: 3 },
  { day: "Wed", calls: 4, leads: 5 },
  { day: "Thu", calls: 11, leads: 2 },
  { day: "Fri", calls: 7, leads: 6 },
  { day: "Sat", calls: 3, leads: 1 },
  { day: "Sun", calls: 1, leads: 0 },
];

export const activityTimeline = {
  "LD-1001": [
    { id: "a1", type: "call", label: "AI call — 3m 16s, marked Interested", time: "Aug 10, 5:40 PM" },
    { id: "a2", type: "note", label: "Wants online ordering before Diwali", time: "Aug 10, 5:45 PM" },
    { id: "a3", type: "status", label: "Status changed Contacted → Interested", time: "Aug 10, 5:46 PM" },
    { id: "a4", type: "followup", label: "Follow-up scheduled Aug 12", time: "Aug 10, 5:47 PM" },
  ],
};
